version: '3.8'
services:
  postgresql:
    image: timescale/timescaledb:latest-pg15
    container_name: owl-postgresql
    command: ["postgres", "-c", "max_locks_per_transaction=256"]
    environment:
      POSTGRES_DB: owlrd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../owlRD/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine  
    command: redis-server --requirepass TeLunSu-36kr
    container_name: owl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: owl-mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 10s
      timeout: 5s
      retries: 5

  sleepace-mysql:
    image: mysql:5.7
    container_name: sleepace-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    volumes:
      - sleepace_mysql_data:/var/lib/mysql
      - ../sleepace/sql:/docker-entrypoint-initdb.d  # 添加SQL初始化脚本
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sleepace-service:
    build:
      context: ../sleepace
      dockerfile: Dockerfile
    container_name: sleepace-service
    ports:
      - "8090:8090"
      - "28070:28070"
      - "29010:29010"   
      #29010 device inital port  28070 device tcp long connect  8090 httpAPI
    volumes:
      - ../sleepace/sleepace-service/log:/var/wisefido/sleepace/sleepace-service/log
    depends_on:
      sleepace-mysql:
        condition: service_healthy
      mqtt:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  sleepace_mysql_data:
    driver: local
  redis_data:
    driver: local