# Mosquitto MQTT Broker 配置文件

# 监听端口
listener 1883
allow_anonymous true

# 日志
log_dest file /mosquitto/log/mosquitto.log
log_type all

# 持久化
persistence true
persistence_location /mosquitto/data/

# WebSocket 支持（端口 9001）
listener 9001
protocol websockets

