# wisefido-qinglan 配置文件

server:
  port: 8081
  address: "0.0.0.0"

mqtt:
  broker: "localhost"
  port: 1883
  username: ""
  password: ""
  client_id: "wisefido-qinglan"

  
  # 雷达设备MQTT主题配置
  radar_device_mqtt:
    server: "10.0.0.30"
    port: 1883
    protocol: 1
    account: "wfiot"
    password: "tt@wf@2025"
    prefix: ""
    product_id: 88
    timeout: 30
    keepalive: 60
    client_id_prefix: "radar"
  
  # 订阅主题
  topics:
    property: "/prop/{productId}/{uid}/post"  # 属性响应主题
    monitor: "/monitor/{productId}/{uid}/post"  # 实时数据主题
    function: "/func/{productId}/{uid}/post"  # 功能响应主题
    stat: "/stat/{productId}/{uid}/post"  # 统计数据主题
    event: "/event/{productId}/{uid}/post"  # 事件主题
    alarm: "/alarm/{productId}/{uid}/post"  # 告警主题

http:
  port: 8081
  host: "0.0.0.0"

redis:
  address: "localhost:6379"
  password: "TeLunSu-36kr"
  db: 0

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres"
  dbname: "owlrd"
  sslmode: "disable"